name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # Step 4: Run Tests
      - name: Run Tests
        run: pytest test_app.py

      # Step 5: Authenticate to Google Cloud
      # Ensure you have added 'GCP_SA_KEY' in GitHub Settings -> Secrets -> Actions
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_ARTIFACT_SA_KEY }}

      # Step 6: Configure Docker to use Google's Registry
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # Step 7: Build and Push with YOUR specific path
      - name: Build and Push to GCP Artifact Registry
        run: |
          docker build -t us-central1-docker.pkg.dev/ci-cd-learning-481620/my-repo/my-app:${{ github.sha }} .
          docker push us-central1-docker.pkg.dev/ci-cd-learning-481620/my-repo/my-app:${{ github.sha }}
